const express = require("express");
const fs = require("fs");

const app = express();

//json middleware to handle post requests
//and get access to req.body
app.use(express.json());

const tours = JSON.parse(
  //readfileSync is NOT asynchronous
  //dont use Sync operations in the callbacks
  //it blocks the event loop
  fs.readFileSync(`${__dirname}/dev-data/data/tours-simple.json`)
);

app.get("/api/v1/tours", (_, res) => {
  res.status(200).json({
    status: "success",
    results: tours.length,
    data: {
      tours,
    },
  });
});

app.post("/api/v1/tours", (req, res) => {
  //Normally Ids are automatically generated by the database.
  const newTourId = tours[tours.length - 1].id + 1;
  const newTour = Object.assign({ id: newTourId, ...req.body });

  //wrtieFileSync will block the event loop
  //dont use it in the callbacks

  tours.push(newTour);

  fs.writeFile(
    `${__dirname}/dev-data/data/tours-simple.json`,
    JSON.stringify(tours),
    (err) => {
      if (err) return console.log("Cannot write to the file.");
      console.log("Added a new Tour successfully");
      res.status(200).json({
        status: "success",
        data: {
          tour: newTour,
        },
      });
    }
  );
});

app.get("/api/v1/tours/:id", (req, res) => {
  const { id } = req.params;
  //Normally Ids are automatically generated by the database.
  //Ids are string so remember to convert them to numbers for manipulation
  if (id >= tours.length) {
    res.status(404).json({
      status: "failed",
      message: "Requested tour not found.",
    });
    return console.log("Requested tour not found");
  }
  const requestedTour = tours.find((tour) => tour.id === +id);
  console.log(requestedTour);
  res.status(200).json({
    status: "success",
    data: {
      tour: requestedTour,
    },
  });
});

// app.get("/", (req, res) => {
//   console.log(req);
//   res.status(200).json({
//     message: "Hello from the server side...",
//     appName: "tours with node",
//   });
// });

// app.post("/", (req, res) => {
//   res.send("You can post the data to this endpoint.");
// });

const port = 4000;

app.listen(port, () => {
  console.log(`Listening requests on port ${port}.... `);
});
