const Tour = require('../models/tourModel');

exports.checkBody = (req, res, next) => {
  if (!req.body.name || !req.body.price) {
    return res.status(400).json({
      status: 'failed',
      message:
        'Insufficient Data to create a tour! Missing Name and Price of Tour',
    });
  }
  next();
};

exports.getAllTours = (req, res) => {
  console.log(req.requestTime);
  res.status(200).json({
    status: 'success',
    requestedAt: req.requestTime,
    // results: tours.length,
    // data: {
    //   tours,
    // },
  });
};

exports.createATour = async (req, res) => {
  try {
    const newTour = await Tour.create(req.body);
    res.status(201).json({
      status: 'success',
      data: {
        tour: newTour,
      },
    });
  } catch (err) {
    res.status(400).json({
      status: 'failed',
      message: err,
    });
  }
};

exports.getATour = (req, res) => {
  //const { id } = req.params;
  //Normally Ids are automatically generated by the database.
  //Ids are string so remember to convert them to numbers for manipulation
  //const requestedTour = tours.find((tour) => tour.id === +id);
  res.status(200).json({
    status: 'success',
    // data: {
    //   tour: requestedTour,
    // },
  });
};

exports.updateATour = (req, res) => {
  //Not a complete implementation of PATCH HTTP Method
  //A complete implementation will require us to change the local files
  //const { id } = req.params;
  //Normally Ids are automatically generated by the database.
  //Ids are string so remember to convert them to numbers for manipulation

  res.status(200).json({
    status: 'success',
    // data: {
    //   updatedTourData: req.body,
    //   tour: tours[id],
    // },
  });
};

exports.deleteATour = (req, res) => {
  //Not a complete implementation of DELETE HTTP Method
  const { id } = req.params;
  console.log(id);
  //Normally Ids are automatically generated by the database.
  //Ids are string so remember to convert them to numbers for manipulation

  res.status(204).json({
    status: 'success',
    data: null,
  });
};
